In [1]:
import pandas as pd

In [2]:
dec_2018 = pd.read_csv("Resources/Dec_4_2018_Data.csv")

In [3]:
dec_2018.head(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,254,2018-11-01 00:00:12.9100,2018-11-01 00:04:27.3870,3522.0,37 St & 24 Ave,40.770148,-73.912094,3513.0,21 St & Hoyt Ave S,40.774645,-73.923706,34117,Subscriber,1992,1
1,833,2018-11-01 00:00:16.3440,2018-11-01 00:14:09.4320,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,251.0,Mott St & Prince St,40.723180,-73.994800,32569,Subscriber,1986,2
2,683,2018-11-01 00:00:17.6630,2018-11-01 00:11:40.9170,3405.0,5 St & 6 Ave,40.670484,-73.982090,3584.0,Eastern Pkwy & Franklin Ave,40.670777,-73.957680,15795,Subscriber,1985,1
3,1840,2018-11-01 00:00:18.7970,2018-11-01 00:30:59.3050,3150.0,E 85 St & York Ave,40.775369,-73.948034,297.0,E 15 St & 3 Ave,40.734232,-73.986923,33290,Subscriber,1994,1
4,1212,2018-11-01 00:00:47.3230,2018-11-01 00:20:59.8840,325.0,E 19 St & 3 Ave,40.736245,-73.984738,212.0,W 16 St & The High Line,40.743349,-74.006818,17411,Subscriber,1989,1
5,792,2018-11-01 00:01:07.6490,2018-11-01 00:14:20.1120,303.0,Mercer St & Spring St,40.723627,-73.999496,3260.0,Mercer St & Bleecker St,40.727064,-73.996621,15344,Customer,1995,2
6,243,2018-11-01 00:01:12.1010,2018-11-01 00:05:15.3940,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3562.0,Classon Ave & St Marks Ave,40.676520,-73.959608,34053,Subscriber,1980,2
7,460,2018-11-01 00:01:12.4060,2018-11-01 00:08:53.2740,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,477.0,W 41 St & 8 Ave,40.756405,-73.990026,14992,Subscriber,1970,1
8,778,2018-11-01 00:01:14.6240,2018-11-01 00:14:13.3190,3579.0,Sterling Pl & Bedford Ave,40.672695,-73.954131,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,35229,Subscriber,1980,2
9,178,2018-11-01 00:01:32.0970,2018-11-01 00:04:30.1980,3467.0,W Broadway & Spring Street,40.724947,-74.001659,151.0,Cleveland Pl & Spring St,40.722104,-73.997249,31476,Subscriber,1978,1

In [4]:
dec_2018.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [6]:
dec_2018.count()

tripduration               1260355
starttime                  1260355
stoptime                   1260355
start station id           1260275
start station name         1260275
start station latitude     1260355
start station longitude    1260355
end station id             1260275
end station name           1260275
end station latitude       1260355
end station longitude      1260355
bikeid                     1260355
usertype                   1260355
birth year                 1260355
gender                     1260355
dtype: int64

In [7]:
dec_2018['birth year'].min()

1885

In [8]:
dec_2018['birth year'].max()

2002

In [11]:
dec_2018 = dec_2018[~(dec_2018['birth year'] < 1960)]

In [12]:
dec_2018.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,254,2018-11-01 00:00:12.9100,2018-11-01 00:04:27.3870,3522.0,37 St & 24 Ave,40.770148,-73.912094,3513.0,21 St & Hoyt Ave S,40.774645,-73.923706,34117,Subscriber,1992,1
1,833,2018-11-01 00:00:16.3440,2018-11-01 00:14:09.4320,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,251.0,Mott St & Prince St,40.723180,-73.994800,32569,Subscriber,1986,2
2,683,2018-11-01 00:00:17.6630,2018-11-01 00:11:40.9170,3405.0,5 St & 6 Ave,40.670484,-73.982090,3584.0,Eastern Pkwy & Franklin Ave,40.670777,-73.957680,15795,Subscriber,1985,1
3,1840,2018-11-01 00:00:18.7970,2018-11-01 00:30:59.3050,3150.0,E 85 St & York Ave,40.775369,-73.948034,297.0,E 15 St & 3 Ave,40.734232,-73.986923,33290,Subscriber,1994,1
4,1212,2018-11-01 00:00:47.3230,2018-11-01 00:20:59.8840,325.0,E 19 St & 3 Ave,40.736245,-73.984738,212.0,W 16 St & The High Line,40.743349,-74.006818,17411,Subscriber,1989,1

In [13]:
dec_2018.count()

tripduration               1178010
starttime                  1178010
stoptime                   1178010
start station id           1177930
start station name         1177930
start station latitude     1178010
start station longitude    1178010
end station id             1177930
end station name           1177930
end station latitude       1178010
end station longitude      1178010
bikeid                     1178010
usertype                   1178010
birth year                 1178010
gender                     1178010
dtype: int64

In [14]:
dec_2018 = dec_2018.dropna(how='any',axis=0)

In [15]:
dec_2018.count()

tripduration               1177930
starttime                  1177930
stoptime                   1177930
start station id           1177930
start station name         1177930
start station latitude     1177930
start station longitude    1177930
end station id             1177930
end station name           1177930
end station latitude       1177930
end station longitude      1177930
bikeid                     1177930
usertype                   1177930
birth year                 1177930
gender                     1177930
dtype: int64

In [16]:
dec_2018.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,254,2018-11-01 00:00:12.9100,2018-11-01 00:04:27.3870,3522.0,37 St & 24 Ave,40.770148,-73.912094,3513.0,21 St & Hoyt Ave S,40.774645,-73.923706,34117,Subscriber,1992,1
1,833,2018-11-01 00:00:16.3440,2018-11-01 00:14:09.4320,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,251.0,Mott St & Prince St,40.723180,-73.994800,32569,Subscriber,1986,2
2,683,2018-11-01 00:00:17.6630,2018-11-01 00:11:40.9170,3405.0,5 St & 6 Ave,40.670484,-73.982090,3584.0,Eastern Pkwy & Franklin Ave,40.670777,-73.957680,15795,Subscriber,1985,1
3,1840,2018-11-01 00:00:18.7970,2018-11-01 00:30:59.3050,3150.0,E 85 St & York Ave,40.775369,-73.948034,297.0,E 15 St & 3 Ave,40.734232,-73.986923,33290,Subscriber,1994,1
4,1212,2018-11-01 00:00:47.3230,2018-11-01 00:20:59.8840,325.0,E 19 St & 3 Ave,40.736245,-73.984738,212.0,W 16 St & The High Line,40.743349,-74.006818,17411,Subscriber,1989,1

In [25]:
dec_2018.to_csv("dec_2018.csv", index=False)